services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: urlshortner-backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongodb:27017/urlshortner
      JWT_SECRET: mySuperSecretKey123456789
      APP_URL: http://localhost:3000/
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: urlshortner-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
